Use sccache instead of ccache (#99)
Closes #86.

This requires https://github.com/mozilla/sccache/pull/1109, which has been merged but hasn't been released yet. Therefore we use our own sccache binary which includes this feature. We'll use the upstream binary once sccache 0.3.0 is out.

In the Ubuntu 20.04 image, this undoes a fix for #80 because that fix never worked in the first place. See #101.

diff --git a/build-jemalloc b/build-jemalloc
--- a/build-jemalloc
+++ b/build-jemalloc
@@ -10,7 +10,9 @@ ENVIRONMENT_NAME=
 SOURCE_PATH=
 OUTPUT_PATH=
 BUILD_CONCURRENCY=1
-CACHE_PATH=
+CACHE_CONNECTION_STRING_FILE=
+CACHE_CONTAINER=
+CACHE_KEY_PREFIX=
 
 function usage()
 {
@@ -18,22 +20,23 @@ function usage()
     echo "Build a Jemalloc binary tarball from its source tarball."
     echo
     echo "Required options:"
-    echo "  -n NAME     Name of environment to build in (one of: $(list_environment_names "$SELFDIR/environments"))"
-    echo "  -s PATH     Path to Jemalloc source tarball"
-    echo "  -o PATH     Path to output tarball"
+    echo "  -n NAME      Name of environment to build in (one of: $(list_environment_names "$SELFDIR/environments"))"
+    echo "  -s PATH      Path to Jemalloc source tarball"
+    echo "  -o PATH      Path to output tarball"
     echo
     echo "Optional options:"
-    echo "  -j NUM      Build concurrency (default: $BUILD_CONCURRENCY)"
-    echo "  -c PATH     Use given directory as cache"
-    echo "  -h          Show usage"
+    echo "  -j NUM       Build concurrency (default: $BUILD_CONCURRENCY)"
+    echo "  -c PATH      Cache to Azure Blob Storage, use connection string in given file"
+    echo "  -r CONTAINER Use given Azure Blob Storage container"
+    echo "  -d NAME      Use given Azure Blob Storage key prefix"
+    echo "  -h           Show usage"
 }
 
 function parse_options()
 {
     local OPTIND=1
-    local ORIG_ARGV
     local opt
-    while getopts "n:s:o:j:c:h" opt; do
+    while getopts "n:s:o:j:c:r:d:h" opt; do
         case "$opt" in
         n)
             ENVIRONMENT_NAME="$OPTARG"
@@ -48,7 +51,13 @@ function parse_options()
             BUILD_CONCURRENCY="$OPTARG"
             ;;
         c)
-            CACHE_PATH=$(absolute_path "$OPTARG")
+            CACHE_CONNECTION_STRING_FILE=$(absolute_path "$OPTARG")
+            ;;
+        r)
+            CACHE_CONTAINER="$OPTARG"
+            ;;
+        d)
+            CACHE_KEY_PREFIX="$OPTARG"
             ;;
         h)
             usage
@@ -62,7 +71,6 @@ function parse_options()
 
     (( OPTIND -= 1 )) || true
     shift $OPTIND || true
-    ORIG_ARGV=("$@")
 
     if [[ "$ENVIRONMENT_NAME" = "" ]]; then
         echo 'ERROR: please specify an environment name with -n.' >&2
@@ -80,8 +88,8 @@ function parse_options()
         echo 'ERROR: please specify an output tarball path with -o.' >&2
         exit 1
     fi
-    if [[ "$CACHE_PATH" != "" && ! -e "$CACHE_PATH" ]]; then
-        echo "ERROR: $CACHE_PATH does not exist." >&2
+    if [[ -n "$CACHE_CONNECTION_STRING_FILE" && -z "$CACHE_CONTAINER" ]]; then
+        echo "ERROR: if a cache connection string file is given, then an Azure Blob Storage container name must also be given." >&2
         exit 1
     fi
 }
@@ -93,8 +101,8 @@ if tty -s; then
 else
     TTY_ARGS=()
 fi
-if [[ "$CACHE_PATH" != "" ]]; then
-    CACHE_PATH_MOUNT_ARGS=(-v "$CACHE_PATH:/cache:delegated")
+if [[ -n "$CACHE_CONNECTION_STRING_FILE" ]]; then
+    CACHE_PATH_MOUNT_ARGS=(-v "$CACHE_CONNECTION_STRING_FILE:/azure-connection-string.txt:ro")
 else
     CACHE_PATH_MOUNT_ARGS=()
 fi
@@ -118,6 +126,8 @@ verbose_run docker run --rm --init "${TTY_ARGS[@]}" \
     "${CACHE_PATH_MOUNT_ARGS[@]}" \
     -e "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" \
     -e "BUILD_CONCURRENCY=$BUILD_CONCURRENCY" \
+    -e "CACHE_CONTAINER=$CACHE_CONTAINER" \
+    -e "CACHE_KEY_PREFIX=$CACHE_KEY_PREFIX" \
     --user "$(id -u):$(id -g)" \
     "fullstaq/ruby-build-env-$ENVIRONMENT_NAME:$IMAGE_VERSION" \
     /system/container-entrypoints/build-jemalloc
