Work in progress

diff --git a/build-ruby b/build-ruby
--- a/build-ruby
+++ b/build-ruby
@@ -8,22 +8,28 @@ source "$SELFDIR/lib/library.sh"
 
 ENVIRONMENT_NAME=
 SOURCE_PATH=
+VERSION=
+JEMALLOC_BIN_PATH=
 OUTPUT_PATH=
 BUILD_CONCURRENCY=1
+CACHE_PATH=
 
 function usage()
 {
-    echo "Usage: ./build-jemalloc <OPTIONS>"
-    echo "Build a Jemalloc binary tarball from its source tarball."
+    echo "Usage: ./build-ruby <OPTIONS>"
+    echo "Build a Ruby binary tarball from its source tarball."
     echo
     echo "Required options:"
-    echo "  -n NAME    Name of environment to build in (one of: $(list_environment_names "$SELFDIR/environments"))"
-    echo "  -s PATH    Path to Jemalloc source tarball"
-    echo "  -o PATH    Path to output tarball"
+    echo "  -n NAME     Name of environment to build in (one of: $(list_environment_names "$SELFDIR/environments"))"
+    echo "  -s PATH     Path to Ruby source tarball"
+    echo "  -v VERSION  Package version number"
+    echo "  -m PATH     Path to Jemalloc binary tarball (as built by ./build-jemalloc)"
+    echo "  -o PATH     Path to output tarball"
     echo
     echo "Optional options:"
-    echo "  -j NUM     Build concurrency (default: $BUILD_CONCURRENCY)"
-    echo "  -h         Show usage"
+    echo "  -j NUM      Build concurrency (default: $BUILD_CONCURRENCY)"
+    echo "  -c PATH     Use given directory as cache"
+    echo "  -h          Show usage"
 }
 
 function parse_options()
@@ -31,7 +37,7 @@ function parse_options()
     local OPTIND=1
     local ORIG_ARGV
     local opt
-    while getopts "n:s:o:j:h" opt; do
+    while getopts "n:s:v:m:o:j:c:h" opt; do
         case "$opt" in
         n)
             ENVIRONMENT_NAME="$OPTARG"
@@ -39,11 +45,20 @@ function parse_options()
         s)
             SOURCE_PATH=$(absolute_path "$OPTARG")
             ;;
+        v)
+            VERSION="$OPTARG"
+            ;;
+        m)
+            JEMALLOC_BIN_PATH=$(absolute_path "$OPTARG")
+            ;;
         o)
             OUTPUT_PATH=$(absolute_path "$OPTARG")
             ;;
         j)
             BUILD_CONCURRENCY="$OPTARG"
+            ;;
+        c)
+            CACHE_PATH=$(absolute_path "$OPTARG")
             ;;
         h)
             usage
@@ -71,8 +86,24 @@ function parse_options()
         echo "ERROR: $SOURCE_PATH does not exist." >&2
         exit 1
     fi
+    if [[ "$VERSION" = "" ]]; then
+        echo 'ERROR: please specify a package version number with -v.' >&2
+        exit 1
+    fi
+    if [[ "$JEMALLOC_BIN_PATH" = "" ]]; then
+        echo 'ERROR: please specify a Jemalloc binary tarball path with -m.' >&2
+        exit 1
+    fi
+    if [[ ! -e "$JEMALLOC_BIN_PATH" ]]; then
+        echo "ERROR: $JEMALLOC_BIN_PATH does not exist." >&2
+        exit 1
+    fi
     if [[ "$OUTPUT_PATH" = "" ]]; then
         echo 'ERROR: please specify an output tarball path with -o.' >&2
+        exit 1
+    fi
+    if [[ "$CACHE_PATH" != "" && ! -e "$CACHE_PATH" ]]; then
+        echo "ERROR: $CACHE_PATH does not exist." >&2
         exit 1
     fi
 }
@@ -84,6 +115,11 @@ if tty -s; then
 else
     TTY_ARGS=()
 fi
+if [[ "$CACHE_PATH" != "" ]]; then
+    CACHE_PATH_MOUNT_ARGS=(-v "$CACHE_PATH:/cache:delegated")
+else
+    CACHE_PATH_MOUNT_ARGS=()
+fi
 
 IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/$ENVIRONMENT_NAME/image_tag")
 create_file_if_missing "$OUTPUT_PATH"
@@ -91,9 +127,12 @@ create_file_if_missing "$OUTPUT_PATH"
 echo '--- Entering Docker container ---'
 verbose_exec docker run --rm --init "${TTY_ARGS[@]}" \
     -v "$SELFDIR:/system:ro" \
-    -v "$SOURCE_PATH:/input/jemalloc-src.tar.bz2:ro" \
-    -v "$OUTPUT_PATH:/output/jemalloc-bin.tar.gz" \
+    -v "$SOURCE_PATH:/input/ruby-src.tar.gz:ro" \
+    -v "$JEMALLOC_BIN_PATH:/input/jemalloc-bin.tar.gz:ro" \
+    -v "$OUTPUT_PATH:/output/ruby-bin.tar.gz" \
+    "${CACHE_PATH_MOUNT_ARGS[@]}" \
     -e "BUILD_CONCURRENCY=$BUILD_CONCURRENCY" \
+    -e "VERSION=$VERSION" \
     --user "$(id -u):$(id -g)" \
     "fullstaq/ruby-build-env-$ENVIRONMENT_NAME:$IMAGE_VERSION" \
-    /system/container-entrypoints/build-jemalloc
+    /system/container-entrypoints/build-ruby
