Work in progress

diff --git a/build-jemalloc b/build-jemalloc
--- a/build-jemalloc
+++ b/build-jemalloc
@@ -10,6 +10,7 @@ ENVIRONMENT_NAME=
 SOURCE_PATH=
 OUTPUT_PATH=
 BUILD_CONCURRENCY=1
+CACHE_PATH=
 
 function usage()
 {
@@ -17,13 +18,14 @@ function usage()
     echo "Build a Jemalloc binary tarball from its source tarball."
     echo
     echo "Required options:"
-    echo "  -n NAME    Name of environment to build in (one of: $(list_environment_names "$SELFDIR/environments"))"
-    echo "  -s PATH    Path to Jemalloc source tarball"
-    echo "  -o PATH    Path to output tarball"
+    echo "  -n NAME     Name of environment to build in (one of: $(list_environment_names "$SELFDIR/environments"))"
+    echo "  -s PATH     Path to Jemalloc source tarball"
+    echo "  -o PATH     Path to output tarball"
     echo
     echo "Optional options:"
-    echo "  -j NUM     Build concurrency (default: $BUILD_CONCURRENCY)"
-    echo "  -h         Show usage"
+    echo "  -j NUM      Build concurrency (default: $BUILD_CONCURRENCY)"
+    echo "  -c PATH     Use given directory as cache"
+    echo "  -h          Show usage"
 }
 
 function parse_options()
@@ -31,7 +33,7 @@ function parse_options()
     local OPTIND=1
     local ORIG_ARGV
     local opt
-    while getopts "n:s:o:j:h" opt; do
+    while getopts "n:s:o:j:c:h" opt; do
         case "$opt" in
         n)
             ENVIRONMENT_NAME="$OPTARG"
@@ -44,6 +46,9 @@ function parse_options()
             ;;
         j)
             BUILD_CONCURRENCY="$OPTARG"
+            ;;
+        c)
+            CACHE_PATH=$(absolute_path "$OPTARG")
             ;;
         h)
             usage
@@ -75,6 +80,10 @@ function parse_options()
         echo 'ERROR: please specify an output tarball path with -o.' >&2
         exit 1
     fi
+    if [[ "$CACHE_PATH" != "" && ! -e "$CACHE_PATH" ]]; then
+        echo "ERROR: $CACHE_PATH does not exist." >&2
+        exit 1
+    fi
 }
 
 parse_options "$@"
@@ -83,6 +92,11 @@ if tty -s; then
     TTY_ARGS=(-t -i)
 else
     TTY_ARGS=()
+fi
+if [[ "$CACHE_PATH" != "" ]]; then
+    CACHE_PATH_MOUNT_ARGS=(-v "$CACHE_PATH:/cache:delegated")
+else
+    CACHE_PATH_MOUNT_ARGS=()
 fi
 
 IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/$ENVIRONMENT_NAME/image_tag")
@@ -93,6 +107,7 @@ verbose_exec docker run --rm --init "${TTY_ARGS[@]}" \
     -v "$SELFDIR:/system:ro" \
     -v "$SOURCE_PATH:/input/jemalloc-src.tar.bz2:ro" \
     -v "$OUTPUT_PATH:/output/jemalloc-bin.tar.gz" \
+    "${CACHE_PATH_MOUNT_ARGS[@]}" \
     -e "BUILD_CONCURRENCY=$BUILD_CONCURRENCY" \
     --user "$(id -u):$(id -g)" \
     "fullstaq/ruby-build-env-$ENVIRONMENT_NAME:$IMAGE_VERSION" \
diff --git a/build-ruby b/build-ruby
--- a/build-ruby
+++ b/build-ruby
@@ -79,7 +79,7 @@ function parse_options()
         exit 1
     fi
     if [[ "$SOURCE_PATH" = "" ]]; then
-        echo 'ERROR: please specify a Jemalloc source tarball path with -s.' >&2
+        echo 'ERROR: please specify a Ruby source tarball path with -s.' >&2
         exit 1
     fi
     if [[ ! -e "$SOURCE_PATH" ]]; then
diff --git a/scripts/autodetect-shlib-dependencies b/scripts/autodetect-shlib-dependencies
--- a/scripts/autodetect-shlib-dependencies
+++ b/scripts/autodetect-shlib-dependencies
@@ -1,4 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env ruby
+# encoding: utf-8
+#
 # Usage: ./scripts/autodetect-shlib-dependencies
 #
 # This script autodetects shared library dependencies of all
@@ -41,50 +43,111 @@
 #     libruby 2.6.1 foo
 #     libjemalloc 2 foo
 
-set -e
-set -o pipefail
+require 'fileutils'
+require 'tempfile'
 
-# shellcheck source=lib/library.sh
-source "$SELFDIR/../lib/library.sh"
+DUMMY_PACKAGE_NAME = 'foo'
 
-TEMP_DIR=$(mktemp -d /tmp/shlibdeps.XXXXXX)
-function _cleanup()
-{
-	rm -rf "$TEMP_DIR"
-}
+def capture!(*command)
+  data = IO.popen(command + [in: :in], 'r:utf-8') do |io|
+    io.read
+  end
+  if $?.exitstatus != 0
+    abort "ERROR: command failed: #{command.join(' ')}"
+  else
+    data
+  end
+end
 
+def list_executable_and_library_files
+  executables = capture!('find', '.', '-executable', '-type', 'f').split("\n").sort
+  libs = capture!('find', '.', '-name', '*.so').split("\n").sort
+  [executables, libs]
+end
 
-DUMMY_PACKAGE_NAME=foo
-PWD=$(pwd)
-LIBS=($( find "$PWD" -name '*.so' ))
-ALL_FILES=($( (find "$PWD" -executable -type f && find "$PWD" -name '*.so' ) | sort -u ))
+def create_dummy_debian_dir
+  begin
+    FileUtils.mkdir_p('debian/root/DEBIAN')
+    File.open('debian/control', 'w:utf-8') do |f|
+      f.write(
+        "Source: $DUMMY_PACKAGE_NAME\n" \
+        "Section: devel\n" \
+        "Priority: optional\n" \
+        "Maintainer: John Doe <john@doe.com>\n" \
+        "\n" \
+        "Package: #{DUMMY_PACKAGE_NAME}\n" \
+        "Architecture: any\n" \
+        "Description: #{DUMMY_PACKAGE_NAME}\n"
+      )
+    end
+    yield
+  ensure
+    FileUtils.remove_entry_secure('debian')
+  end
+end
 
-cd "$TEMP_DIR"
-mkdir debian
-mkdir -p debian/root/DEBIAN
+def create_debian_shlibs_file(libs)
+  File.open('debian/root/DEBIAN/shlibs', 'w:utf-8') do |f|
+    libs.each do |lib|
+      soname_lines = capture!('objdump', '-p', lib).split("\n").grep(/SONAME/)
+      next if soname_lines.empty?
 
-cat > debian/control <<EOF
-Source: $DUMMY_PACKAGE_NAME
-Section: devel
-Priority: optional
-Maintainer: John Doe <john@doe.com>
+      soname = soname_lines[0].strip.split(/ +/)[1]
+      next if soname.empty?
 
-Package: $DUMMY_PACKAGE_NAME
-Architecture: any
-Description: $DUMMY_PACKAGE_NAME
-EOF
+      sobarename = soname.sub(/\.so\..*/, '')
+      soversion = soname.sub(/.*\.so\./, '')
 
-for LIB in "${LIBS[@]}"; do
-	SONAME=$(objdump -p "$LIB" | grep SONAME | awk '{ print $2 }')
-	SOBARENAME=$(echo "$SONAME" | sed 's/\.so\..*//')
-	SOVERSION=$(echo "$SONAME" | sed 's/.*\.so\.//')
-	if [[ "$SONAME" != "" && "$SOVERSION" != "" ]]; then
-		echo "$SOBARENAME $SOVERSION $DUMMY_PACKAGE_NAME" >> debian/root/DEBIAN/shlibs
-	fi
-done
+      if !soversion.empty?
+        f.puts "#{sobarename} #{soversion} #{DUMMY_PACKAGE_NAME}"
+      end
+    end
+  end
+end
 
-# dpkg-shlibdeps outputs something like:
-# shlibs:Depends=foo, libc6 (>= 2.25), zlib1g (>= 1:1.1.4)
-#
-# There may be multiple lines like these.
-dpkg-shlibdeps -O "${FILES[@]}" | sed -E 's/.*?=//'
+def run_dpkg_shlibdeps(executables, libs)
+  # dpkg-shlibdeps outputs something like:
+  # shlibs:Depends=foo, libc6 (>= 2.25), zlib1g (>= 1:1.1.4)
+  #
+  # There may be multiple lines like these.
+
+  all_files = [executables, libs].sort.uniq
+  command = ['dpkg-shlibdeps', '-O', all_files].flatten
+
+  Tempfile.open('dpkg-shlibdeps-stderr', encoding: 'utf-8') do |tmpfile|
+    result = []
+
+    IO.popen(command + [in: :in, err: tmpfile], 'r:utf-8') do |io|
+      io.each_line do |line|
+        result.concat(line.strip.sub(/.*?=/, '').split(/ *, */))
+      end
+    end
+
+    result.delete(DUMMY_PACKAGE_NAME)
+
+    # Print dpkg-shlibdeps stderr except for some expected and
+    # uninteresting messages.
+    tmpfile.rewind
+    stderr_lines = tmpfile.read.split("\n")
+    stderr_lines.reject! do |line|
+      line =~ /binaries to analyze should already be installed in their package's directory/
+    end
+    STDERR.puts stderr_lines
+    puts result.join(', ')
+
+    if $?.exitstatus != 0
+      abort "ERROR: command failed: dpkg-shlibdeps -O <FILES...>"
+    end
+  end
+end
+
+def main
+  Dir.chdir(ARGV[0]) if ARGV[0]
+  executables, libs = list_executable_and_library_files
+  create_dummy_debian_dir do
+    create_debian_shlibs_file(libs)
+    run_dpkg_shlibdeps(executables, libs)
+  end
+end
+
+main
