Work in progress

diff --git a/build-rbenv-deb b/build-rbenv-deb
--- a/build-rbenv-deb
+++ b/build-rbenv-deb
@@ -6,20 +6,18 @@ SELFDIR=$(cd "$SELFDIR" && pwd)
 # shellcheck source=lib/library.sh
 source "$SELFDIR/lib/library.sh"
 
-BINARY_TARBALL_PATH=
+SOURCE_PATH=
 OUTPUT_PATH=
-DISTRO=
 REVISION=0
 
 function usage()
 {
-    echo "Usage: ./build-rpm <OPTIONS>"
-    echo "Build a Ruby RPM package from its binary tarball (which is produced by ./build-ruby)."
+    echo "Usage: ./build-rbenv-deb <OPTIONS>"
+    echo "Build an Rbenv Debian package."
     echo
     echo "Required options:"
-    echo "  -b PATH     Path to Ruby binary tarball (as built by ./build-ruby)"
+    echo "  -s PATH     Path to Rbenv source tree"
     echo "  -o PATH     Path to output package file"
-    echo "  -d DISTRO   Name of distribution for which package is intended (e.g. centos7)"
     echo
     echo "Optional options:"
     echo "  -r REVISION Package revision number (default: $REVISION)"
@@ -31,16 +29,13 @@ function parse_options()
     local OPTIND=1
     local ORIG_ARGV
     local opt
-    while getopts "b:o:d:r:h" opt; do
+    while getopts "s:o:r:h" opt; do
         case "$opt" in
-        b)
-            BINARY_TARBALL_PATH=$(absolute_path "$OPTARG")
+        s)
+            SOURCE_PATH=$(absolute_path "$OPTARG")
             ;;
         o)
             OUTPUT_PATH=$(absolute_path "$OPTARG")
-            ;;
-        d)
-            DISTRO="$OPTARG"
             ;;
         r)
             REVISION="$OPTARG"
@@ -59,20 +54,16 @@ function parse_options()
     shift $OPTIND || true
     ORIG_ARGV=("$@")
 
-    if [[ "$BINARY_TARBALL_PATH" = "" ]]; then
-        echo 'ERROR: please specify a Ruby binary tarball path with -b.' >&2
+    if [[ "$SOURCE_PATH" = "" ]]; then
+        echo 'ERROR: please specify an Rbenv source path with -s.' >&2
         exit 1
     fi
-    if [[ ! -e "$BINARY_TARBALL_PATH" ]]; then
-        echo "ERROR: $BINARY_TARBALL_PATH does not exist." >&2
+    if [[ ! -e "$SOURCE_PATH" ]]; then
+        echo "ERROR: $SOURCE_PATH does not exist." >&2
         exit 1
     fi
     if [[ "$OUTPUT_PATH" = "" ]]; then
         echo 'ERROR: please specify an output package path with -o.' >&2
-        exit 1
-    fi
-    if [[ "$DISTRO" = "" ]]; then
-        echo 'ERROR: please specify a distribution name with -d.' >&2
         exit 1
     fi
 }
@@ -85,16 +76,15 @@ else
     TTY_ARGS=()
 fi
 
-IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/rpm-utility/image_tag")
+IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/utility/image_tag")
 create_file_if_missing "$OUTPUT_PATH"
 
 echo '--- Entering Docker container ---'
 verbose_exec docker run --rm --init "${TTY_ARGS[@]}" \
     -v "$SELFDIR:/system:ro" \
-    -v "$BINARY_TARBALL_PATH:/input/ruby-bin.tar.gz:ro" \
-    -v "$OUTPUT_PATH:/output/ruby.rpm" \
+    -v "$SOURCE_PATH:/input/rbenv:ro" \
+    -v "$OUTPUT_PATH:/output/rbenv.deb" \
     -e "REVISION=$REVISION" \
-    -e "DISTRO=$DISTRO" \
     --user "$(id -u):$(id -g)" \
     "fullstaq/ruby-build-env-utility:$IMAGE_VERSION" \
-    /system/container-entrypoints/build-rpm
+    /system/container-entrypoints/build-rbenv-deb
