Work in progress

diff --git a/build-ruby b/build-ruby
--- a/build-ruby
+++ b/build-ruby
@@ -8,9 +8,10 @@ source "$SELFDIR/lib/library.sh"
 
 ENVIRONMENT_NAME=
 SOURCE_PATH=
-VERSION=
-JEMALLOC_BIN_PATH=
+PACKAGE_VERSION=
 OUTPUT_PATH=
+VARIANT=normal
+JEMALLOC_BIN_PATH=
 BUILD_CONCURRENCY=1
 CACHE_PATH=
 
@@ -23,8 +24,11 @@ function usage()
     echo "  -n NAME     Name of environment to build in (one of: $(list_environment_names "$SELFDIR/environments"))"
     echo "  -s PATH     Path to Ruby source tarball"
     echo "  -v VERSION  Package version number"
-    echo "  -m PATH     Path to Jemalloc binary tarball (as built by ./build-jemalloc)"
     echo "  -o PATH     Path to output tarball"
+    echo
+    echo "Build variant (required):"
+    echo "  -m PATH     Build with Jemalloc support, using this Jemalloc binary tarball (as built by ./build-jemalloc)"
+    echo "  -t          Build with malloc_trim support"
     echo
     echo "Optional options:"
     echo "  -j NUM      Build concurrency (default: $BUILD_CONCURRENCY)"
@@ -37,7 +41,7 @@ function parse_options()
     local OPTIND=1
     local ORIG_ARGV
     local opt
-    while getopts "n:s:v:m:o:j:c:h" opt; do
+    while getopts "n:s:v:o:m:tj:c:h" opt; do
         case "$opt" in
         n)
             ENVIRONMENT_NAME="$OPTARG"
@@ -46,13 +50,17 @@ function parse_options()
             SOURCE_PATH=$(absolute_path "$OPTARG")
             ;;
         v)
-            VERSION="$OPTARG"
-            ;;
-        m)
-            JEMALLOC_BIN_PATH=$(absolute_path "$OPTARG")
+            PACKAGE_VERSION="$OPTARG"
             ;;
         o)
             OUTPUT_PATH=$(absolute_path "$OPTARG")
+            ;;
+        m)
+            VARIANT=jemalloc
+            JEMALLOC_BIN_PATH=$(absolute_path "$OPTARG")
+            ;;
+        t)
+            VARIANT=malloctrim
             ;;
         j)
             BUILD_CONCURRENCY="$OPTARG"
@@ -86,17 +94,19 @@ function parse_options()
         echo "ERROR: $SOURCE_PATH does not exist." >&2
         exit 1
     fi
-    if [[ "$VERSION" = "" ]]; then
+    if [[ "$PACKAGE_VERSION" = "" ]]; then
         echo 'ERROR: please specify a package version number with -v.' >&2
         exit 1
     fi
-    if [[ "$JEMALLOC_BIN_PATH" = "" ]]; then
-        echo 'ERROR: please specify a Jemalloc binary tarball path with -m.' >&2
-        exit 1
-    fi
-    if [[ ! -e "$JEMALLOC_BIN_PATH" ]]; then
-        echo "ERROR: $JEMALLOC_BIN_PATH does not exist." >&2
-        exit 1
+    if [[ "$VARIANT" = jemalloc ]]; then
+        if [[ "$JEMALLOC_BIN_PATH" = "" ]]; then
+            echo 'ERROR: please specify a Jemalloc binary tarball path with -m.' >&2
+            exit 1
+        fi
+        if [[ "$JEMALLOC_BIN_PATH" != "" && ! -e "$JEMALLOC_BIN_PATH" ]]; then
+            echo "ERROR: $JEMALLOC_BIN_PATH does not exist." >&2
+            exit 1
+        fi
     fi
     if [[ "$OUTPUT_PATH" = "" ]]; then
         echo 'ERROR: please specify an output tarball path with -o.' >&2
@@ -115,10 +125,12 @@ if tty -s; then
 else
     TTY_ARGS=()
 fi
+MOUNT_ARGS=()
+if [[ "$VARIANT" = jemalloc ]]; then
+    MOUNT_ARGS+=(-v "$JEMALLOC_BIN_PATH:/input/jemalloc-bin.tar.gz:ro")
+fi
 if [[ "$CACHE_PATH" != "" ]]; then
-    CACHE_PATH_MOUNT_ARGS=(-v "$CACHE_PATH:/cache:delegated")
-else
-    CACHE_PATH_MOUNT_ARGS=()
+    MOUNT_ARGS+=(-v "$CACHE_PATH:/cache:delegated")
 fi
 
 IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/$ENVIRONMENT_NAME/image_tag")
@@ -128,11 +140,12 @@ echo '--- Entering Docker container ---'
 verbose_exec docker run --rm --init "${TTY_ARGS[@]}" \
     -v "$SELFDIR:/system:ro" \
     -v "$SOURCE_PATH:/input/ruby-src.tar.gz:ro" \
-    -v "$JEMALLOC_BIN_PATH:/input/jemalloc-bin.tar.gz:ro" \
     -v "$OUTPUT_PATH:/output/ruby-bin.tar.gz" \
-    "${CACHE_PATH_MOUNT_ARGS[@]}" \
+    "${MOUNT_ARGS[@]}" \
+    -e "VARIANT=$VARIANT" \
     -e "BUILD_CONCURRENCY=$BUILD_CONCURRENCY" \
-    -e "VERSION=$VERSION" \
+    -e "PACKAGE_VERSION=$PACKAGE_VERSION" \
+    -e "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" \
     --user "$(id -u):$(id -g)" \
     "fullstaq/ruby-build-env-$ENVIRONMENT_NAME:$IMAGE_VERSION" \
     /system/container-entrypoints/build-ruby
diff --git a/container-entrypoints/build-ruby b/container-entrypoints/build-ruby
--- a/container-entrypoints/build-ruby
+++ b/container-entrypoints/build-ruby
@@ -6,26 +6,35 @@ SELFDIR=$(cd "$SELFDIR" && pwd)
 # shellcheck source=lib/library.sh
 source "$SELFDIR/../lib/library.sh"
 
-JEMALLOC_DIR=/home/builder/jemalloc
 RUBY_SRC_CONTAINER_DIR=/home/builder/ruby-src
 DESTDIR=/home/builder/ruby-inst
 INPUT_PATH=/input/ruby-src.tar.gz
-JEMALLOC_BIN_TARBALL_PATH=/input/jemalloc-bin.tar.gz
 OUTPUT_PATH=/output/ruby-bin.tar.gz
 
 require_container_mount "$INPUT_PATH"
-require_container_mount "$JEMALLOC_BIN_TARBALL_PATH"
 require_container_mount "$OUTPUT_PATH"
-require_container_envvar VERSION
+require_container_envvar PACKAGE_VERSION
+require_container_envvar VARIANT
+require_container_envvar ENVIRONMENT_NAME
+if [[ "$VARIANT" != normal ]]; then
+    VARIANT_SUFFIX="-$VARIANT"
+fi
+if [[ "$VARIANT" = jemalloc ]]; then
+    JEMALLOC_BIN_TARBALL_PATH=/input/jemalloc-bin.tar.gz
+    require_container_mount "$JEMALLOC_BIN_TARBALL_PATH"
+fi
 
 BUILD_CONCURRENCY="${BUILD_CONCURRENCY:-4}"
-INSTALL_PREFIX="/usr/lib/fullstaq-ruby/versions/$VERSION"
+INSTALL_PREFIX="/usr/lib/fullstaq-ruby/versions/$PACKAGE_VERSION$VARIANT_SUFFIX"
 
 
-export C_INCLUDE_PATH="$JEMALLOC_DIR/include"
-export CPLUS_INCLUDE_PATH="$JEMALLOC_DIR/include"
-export LIBRARY_PATH="$JEMALLOC_DIR/lib"
-export LD_LIBRARY_PATH="$JEMALLOC_DIR/lib"
+if [[ "$VARIANT" = jemalloc ]]; then
+    JEMALLOC_DIR=/home/builder/jemalloc
+    export C_INCLUDE_PATH="$JEMALLOC_DIR/include"
+    export CPLUS_INCLUDE_PATH="$JEMALLOC_DIR/include"
+    export LIBRARY_PATH="$JEMALLOC_DIR/lib"
+    export LD_LIBRARY_PATH="$JEMALLOC_DIR/lib"
+fi
 export LD_RUN_PATH="$INSTALL_PREFIX/lib"
 
 
@@ -42,10 +51,18 @@ fi
 echo
 
 
-header "Extracting Jemalloc binaries..."
-run mkdir "$JEMALLOC_DIR"
-run tar -xzf "$JEMALLOC_BIN_TARBALL_PATH" -C "$JEMALLOC_DIR"
-echo
+if [[ "$VARIANT" = jemalloc ]]; then
+    header "Extracting Jemalloc binaries..."
+    run mkdir "$JEMALLOC_DIR"
+    run tar -xzf "$JEMALLOC_BIN_TARBALL_PATH" -C "$JEMALLOC_DIR"
+    JEMALLOC_ENVIRONMENT_NAME=$(cat "$JEMALLOC_DIR/ENVIRONMENT")
+    echo "+ Detected build environment in which Jemalloc was built: $JEMALLOC_ENVIRONMENT_NAME"
+    if [[ "$JEMALLOC_ENVIRONMENT_NAME" != "$ENVIRONMENT_NAME" ]]; then
+        echo "ERROR: we are currently in environment $ENVIRONMENT_NAME, but Jemalloc was built in another environment." >&2
+        exit 1
+    fi
+    echo
+fi
 
 
 header "Extracting Ruby sources..."
@@ -59,9 +76,27 @@ echo
 
 
 header "Configuring and compiling Ruby..."
+if [[ "$VARIANT" = jemalloc ]]; then
+    EXTRA_CONFIGURE_ARGS=(--with-jemalloc)
+    if [[ "$PACKAGE_VERSION" =~ ^2\.5 ]]; then
+        run patch -p1 -ti /system/resources/ruby_25_jemalloc.patch
+    else
+        run patch -p1 -ti /system/resources/ruby_26_jemalloc.patch
+    fi
+elif [[ "$VARIANT" = malloctrim ]]; then
+    EXTRA_CONFIGURE_ARGS=()
+    run patch -p1 -ti /system/resources/ruby_malloctrim.patch
+    if [[ "$PACKAGE_VERSION" =~ ^2\.5 ]]; then
+        run patch -p1 -ti /system/resources/ruby_25_malloctrim.patch
+    else
+        run patch -p1 -ti /system/resources/ruby_26_malloctrim.patch
+    fi
+else
+    EXTRA_CONFIGURE_ARGS=()
+fi
 run ./configure --prefix="$INSTALL_PREFIX" \
     --enable-shared --disable-install-static-library \
-    --with-jemalloc --disable-install-rdoc
+    --disable-install-rdoc "${EXTRA_CONFIGURE_ARGS[@]}"
 run make "-j$BUILD_CONCURRENCY"
 echo
 
@@ -76,11 +111,15 @@ find "$DESTDIR/$INSTALL_PREFIX" -name '*.so' -print0 | xargs -0 strip --strip-de
 
 run rm -rf "$DESTDIR/$INSTALL_PREFIX/share/man"
 run mkdir -p "$DESTDIR/usr/lib/rbenv/versions"
-run ln -s "$INSTALL_PREFIX" "$DESTDIR/usr/lib/rbenv/versions/$VERSION"
+run ln -s "$INSTALL_PREFIX" "$DESTDIR/usr/lib/rbenv/versions/$PACKAGE_VERSION$VARIANT_SUFFIX"
 
 ABI_VERSION=$(ls "$DESTDIR/$INSTALL_PREFIX/lib/ruby/site_ruby")
-run cp -R "$JEMALLOC_DIR"/include/jemalloc "$DESTDIR/$INSTALL_PREFIX/include/ruby-$ABI_VERSION"/
-run cp "$JEMALLOC_DIR"/lib/libjemalloc* "$DESTDIR/$INSTALL_PREFIX"/lib/
+
+if [[ "$VARIANT" = jemalloc ]]; then
+    run cp -R "$JEMALLOC_DIR"/include/jemalloc "$DESTDIR/$INSTALL_PREFIX/include/ruby-$ABI_VERSION"/
+    run cp "$JEMALLOC_DIR"/lib/libjemalloc* "$DESTDIR/$INSTALL_PREFIX"/lib/
+fi
+
 echo
 
 
@@ -91,11 +130,15 @@ if [[ -e /etc/debian_version ]]; then
     export RUBYPATH="$DESTDIR/$INSTALL_PREFIX/bin"
     export RUBYLIB="$DESTDIR/$INSTALL_PREFIX/lib/ruby/$ABI_VERSION:$DESTDIR/$INSTALL_PREFIX/lib/ruby/$ABI_VERSION/$PLATFORM_NAME"
 
-    echo "+ $RUBYPATH/ruby /system/scripts/autodetect-shlib-dependencies $DESTDIR | tee $DESTDIR/shlib-deps.txt"
-    "$RUBYPATH/ruby" /system/scripts/autodetect-shlib-dependencies "$DESTDIR" | tee "$DESTDIR/shlib-deps.txt"
+    echo "+ $RUBYPATH/ruby /system/internal-scripts/autodetect-shlib-dependencies $DESTDIR | tee $DESTDIR/shlib-deps.txt"
+    "$RUBYPATH/ruby" /system/internal-scripts/autodetect-shlib-dependencies "$DESTDIR" | tee "$DESTDIR/shlib-deps.txt"
     echo
 fi
 
 
 header "Packaging up..."
+echo "+ echo $VARIANT > $DESTDIR/VARIANT"
+echo "$VARIANT" > "$DESTDIR/VARIANT"
+echo "+ echo $ENVIRONMENT_NAME > $DESTDIR/ENVIRONMENT"
+echo "$ENVIRONMENT_NAME" > "$DESTDIR/ENVIRONMENT"
 run tar -czf "$OUTPUT_PATH" -C "$DESTDIR" .
diff --git a/test-debs b/test-debs
--- a/test-debs
+++ b/test-debs
@@ -9,6 +9,7 @@ source "$SELFDIR/lib/library.sh"
 RUBY_DEB_PATH=
 RBENV_DEB_PATH=
 IMAGE=
+EXPECTED_VARIANT=
 DEBUG_ON_FAIL=false
 
 function usage()
@@ -20,6 +21,7 @@ function usage()
     echo "  -r PATH     Path to Ruby DEB package"
     echo "  -b PATH     Path to Rbenv DEB package"
     echo "  -i IMAGE    Image name to run test in (e.g. ubuntu:18.04)"
+    echo "  -v VARIANT  Expected variant name (one of: normal, jemalloc, malloctrim)"
     echo
     echo "Optional options:"
     echo "  -D          Open a debug shell on failure"
@@ -31,7 +33,7 @@ function parse_options()
     local OPTIND=1
     local ORIG_ARGV
     local opt
-    while getopts "r:b:i:Dh" opt; do
+    while getopts "r:b:i:v:Dh" opt; do
         case "$opt" in
         r)
             RUBY_DEB_PATH=$(absolute_path "$OPTARG")
@@ -41,6 +43,9 @@ function parse_options()
             ;;
         i)
             IMAGE="$OPTARG"
+            ;;
+        v)
+            EXPECTED_VARIANT="$OPTARG"
             ;;
         D)
             DEBUG_ON_FAIL=true
@@ -79,6 +84,10 @@ function parse_options()
         echo 'ERROR: please specify an image name with -i.' >&2
         exit 1
     fi
+    if [[ "$EXPECTED_VARIANT" != normal && "$EXPECTED_VARIANT" != jemalloc && "$EXPECTED_VARIANT" != malloctrim ]]; then
+        echo 'ERROR: please specify a valid variant name with -v.' >&2
+        exit 1
+    fi
 }
 
 parse_options "$@"
@@ -90,7 +99,7 @@ else
 fi
 
 UTILITY_IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/utility/image_tag")
-RUBY_PACKAGE_VERSION=$(basename "$RUBY_DEB_PATH" | sed 's/_.*//; s/.*-//')
+RUBY_PACKAGE_VERSION=$(basename "$RUBY_DEB_PATH" | sed -E 's/(-[a-zA-Z]+)?_.*//; s/.*-//')
 
 TEMP_DIR=$(mktemp -d /tmp/test.XXXXXX)
 function _cleanup()
@@ -102,8 +111,8 @@ mkdir -p "$TEMP_DIR/repo"
 echo '--- Entering preparation Docker container ---'
 verbose_run docker run --rm --init "${TTY_ARGS[@]}" \
     -v "$SELFDIR:/system:ro" \
-    -v "$RUBY_DEB_PATH:/input/fullstaq-ruby.deb:ro" \
-    -v "$RBENV_DEB_PATH:/input/fullstaq-rbenv.deb:ro" \
+    -v "$RUBY_DEB_PATH:/input/$(basename "$RUBY_DEB_PATH"):ro" \
+    -v "$RBENV_DEB_PATH:/input/$(basename "$RBENV_DEB_PATH"):ro" \
     -v "$TEMP_DIR/repo:/output" \
     --user "$(id -u):$(id -g)" \
     "fullstaq/ruby-build-env-utility:$UTILITY_IMAGE_VERSION" \
@@ -116,6 +125,7 @@ verbose_run docker run --rm --init "${TTY_ARGS[@]}" \
     -v "$SELFDIR:/system:ro" \
     -v "$TEMP_DIR/repo:/input/repo:ro" \
     -e "RUBY_PACKAGE_VERSION=$RUBY_PACKAGE_VERSION" \
+    -e "EXPECTED_VARIANT=$EXPECTED_VARIANT" \
     -e "DEBUG_ON_FAIL=$DEBUG_ON_FAIL" \
     --user root \
     --entrypoint /system/container-entrypoints/test-debs \
diff --git a/test-rpms b/test-rpms
--- a/test-rpms
+++ b/test-rpms
@@ -9,6 +9,7 @@ source "$SELFDIR/lib/library.sh"
 RUBY_RPM_PATH=
 RBENV_RPM_PATH=
 IMAGE=
+EXPECTED_VARIANT=
 DEBUG_ON_FAIL=false
 
 function usage()
@@ -20,6 +21,7 @@ function usage()
     echo "  -r PATH     Path to Ruby RPM package"
     echo "  -b PATH     Path to Rbenv RPM package"
     echo "  -i IMAGE    Image name to run test in (e.g. centos:7)"
+    echo "  -v VARIANT  Expected variant name (one of: normal, jemalloc, malloctrim)"
     echo
     echo "Optional options:"
     echo "  -D          Open a debug shell on failure"
@@ -31,7 +33,7 @@ function parse_options()
     local OPTIND=1
     local ORIG_ARGV
     local opt
-    while getopts "r:b:i:Dh" opt; do
+    while getopts "r:b:i:v:Dh" opt; do
         case "$opt" in
         r)
             RUBY_RPM_PATH=$(absolute_path "$OPTARG")
@@ -41,6 +43,9 @@ function parse_options()
             ;;
         i)
             IMAGE="$OPTARG"
+            ;;
+        v)
+            EXPECTED_VARIANT="$OPTARG"
             ;;
         D)
             DEBUG_ON_FAIL=true
@@ -77,6 +82,10 @@ function parse_options()
     fi
     if [[ "$IMAGE" = "" ]]; then
         echo 'ERROR: please specify an image name with -i.' >&2
+        exit 1
+    fi
+    if [[ "$EXPECTED_VARIANT" != normal && "$EXPECTED_VARIANT" != jemalloc && "$EXPECTED_VARIANT" != malloctrim ]]; then
+        echo 'ERROR: please specify a valid variant name with -v.' >&2
         exit 1
     fi
 }
@@ -116,6 +125,7 @@ verbose_run docker run --rm --init "${TTY_ARGS[@]}" \
     -v "$SELFDIR:/system:ro" \
     -v "$TEMP_DIR/repo:/input/repo:ro" \
     -e "RUBY_PACKAGE_VERSION=$RUBY_PACKAGE_VERSION" \
+    -e "EXPECTED_VARIANT=$EXPECTED_VARIANT" \
     -e "DEBUG_ON_FAIL=$DEBUG_ON_FAIL" \
     --user root \
     --entrypoint /system/container-entrypoints/test-rpms \
