Fix typos

diff --git a/test-debs b/test-debs
--- a/test-debs
+++ b/test-debs
@@ -126,11 +126,11 @@ function parse_options()
         fi
     else
         if [[ "$RUBY_DEB_PATH" != "" ]]; then
-            echo 'ERROR: is -S is given, then -r may not be given.' >&2
+            echo 'ERROR: if -S is given, then -r may not be given.' >&2
             exit 1
         fi
         if [[ "$RBENV_DEB_PATH" != "" ]]; then
-            echo 'ERROR: is -S is given, then -b may not be given.' >&2
+            echo 'ERROR: if -S is given, then -b may not be given.' >&2
             exit 1
         fi
         if [[ "$COMMON_DEB_PATH" != "" ]]; then
diff --git a/test-rpms b/test-rpms
--- a/test-rpms
+++ b/test-rpms
@@ -116,11 +116,11 @@ function parse_options()
         fi
     else
         if [[ "$RUBY_RPM_PATH" != "" ]]; then
-            echo 'ERROR: is -S is given, then -r may not be given.' >&2
+            echo 'ERROR: if -S is given, then -r may not be given.' >&2
             exit 1
         fi
         if [[ "$RBENV_RPM_PATH" != "" ]]; then
-            echo 'ERROR: is -S is given, then -b may not be given.' >&2
+            echo 'ERROR: if -S is given, then -b may not be given.' >&2
             exit 1
         fi
         if [[ "$COMMON_RPM_PATH" != "" ]]; then
