CI/CD: when uploading packages, retry if curl fails on a connection problem
This deals with Bintray flakiness.

Closes #41.

diff --git a/internal-scripts/upload-rpm b/internal-scripts/upload-rpm
--- a/internal-scripts/upload-rpm
+++ b/internal-scripts/upload-rpm
@@ -20,16 +20,22 @@ function upload()
     local REPO_ARCH="$2"
     local REPO_OVERRIDE="$3"
     local PID="$$"
+    local TRY_NUM=1
+    local MAX_TRIES=3
     local -a CURL_COMMAND=(
         curl -sSL --netrc-file /tmp/curl-creds
         -w '%{http_code}' -o "/tmp/body-$PID.txt"
         -X PUT -T "$FILE"
         "https://api.bintray.com/api/v1/content/fullstaq/$REPO_NAME/fullstaq-ruby/all/$REPO_DISTRO/$REPO_ARCH/$BASENAME?override=$REPO_OVERRIDE"
     )
+
     if $DRY_RUN; then
         echo "+ Dry-running: ${CURL_COMMAND[*]}"
-    else
-        echo "+ ${CURL_COMMAND[*]}"
+        return 0
+    fi
+
+    while true; do
+        echo "+ (Try $TRY_NUM/$MAX_TRIES) ${CURL_COMMAND[*]}"
         set +e
         HTTP_CODE=$("${CURL_COMMAND[@]}" 2>"/tmp/stderr-$PID.txt")
         local EXITSTATUS=$?
@@ -37,23 +43,24 @@ function upload()
 
         if [[ "$EXITSTATUS" = 0 ]]; then
             echo "HTTP response code: $HTTP_CODE"
-            # Print body.txt while ensuring that a trailing newline is also
-            # printed.
             echo "HTTP body: $(cat /tmp/body-$$.txt)"
             cat /tmp/stderr-$PID.txt
             if [[ "$HTTP_CODE" =~ ^2 ]] || [[ "$HTTP_CODE" = 409 && "$IGNORE_EXISTING" = true ]]; then
                 return 0
             else
-                echo "*** ERROR DETECTED"
+                echo "${BOLD}${RED}*** ERROR DETECTED${RESET}"
                 return 1
             fi
         else
-            # Print stderr.txt while ensuring that a trailing newline is also
-            # printed.
-            echo "ERROR: $(cat /tmp/stderr-$PID.txt)"
+            echo "${BOLD}${RED}CURL ERROR:${RESET} $(cat /tmp/stderr-$PID.txt)"
+            (( TRY_NUM++ )) || true
+            if [[ $TRY_NUM -gt $MAX_TRIES ]]; then
+                return "$EXITSTATUS"
+            else
+                echo "${BOLD}${YELLOW}*** WARNING: command failed, retrying...${RESET}"
+            fi
         fi
-        return "$EXITSTATUS"
-    fi
+    done
 }
 
 REPO_NAME="$1"
